# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py312"

[lint]
select = [
    "ALL",
]

ignore = [
    "ANN101", # Missing type annotation for `self` in method
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "D203", # no-blank-line-before-class (incompatible with formatter)
    "D212", # multi-line-summary-first-line (incompatible with formatter)
    "COM812", # incompatible with formatter
    "ISC001", # incompatible with formatter
]

[lint.per-file-ignores]
"tests/*" = [
    "S101", # Assert
    "PLR2004", # Magic value comparison
    "PT019", # Fixture
    "PLR0913", # Too many arguments
    "E501", # Lint too long
    "FBT001", # Boolean positional argument
    "FBT002", # Boolean positional argument
    "TRY002", # Exception
    "ARG001", # Unused function
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25
