call:
  name: Call Service
  description: Retry a service call on failure.
  fields:
    service:
      description: The service to retry on failure.
      example: homeassistant.turn_on
    retries:
      description: Max amount of calls (defualt is 7).
      example: 3
